logging:
  file:
    path: ./

spring:
  task:
    execution:
      shutdown:
        await-termination: false
        await-termination-period: 3
      pool:
        core-size: 15
        queue-capacity: 10
        max-size: 20
    scheduling:
      pool:
        size: 15