version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk

    working_directory: ~/retrobot
    
    steps:
      # git pull
      - checkout
      # package into a jar
      - run: mvn clean package
      - run: wget https://github.com/libgdx/packr/releases/download/packr-2.7.0/packr-all-2.7.0.jar
      - run: mv ./target/retrobot-1.0-SNAPSHOT-spring-boot.jar ./target/retrobot.jar
      - run: wget https://download.java.net/java/GA/jdk12/33/GPL/openjdk-12_windows-x64_bin.zip
      - run: java -jar packr-all-2.7.0.jar --platform windows64 --jdk openjdk-12_windows-x64_bin.zip --executable retrobot --classpath ./target/retrobot.jar --mainclass org.springframework.boot.loader.JarLauncher --vmargs Xmx1G --minimizejre soft --output retrobotbuild
      - run: echo "retrobot.exe" >> ./retrobotbuild/start-bot.bat
      - run: mv ./target/scripts ./retrobotbuild
      - run: zip -r retrobot.zip retrobotbuild/*
      - run: curl -F file=@retrobot.zip https://srv-file1.gofile.io/uploadFile
      - store_artifacts:
          path: retrobot.zip

