version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk

    working_directory: ~/retrobot
    
    steps:
      # git pull
      - checkout
      # package into a jar
      - run: mvn clean package

      # build and push docker image to docker hub

      # store raw contents of src code
      - store_artifacts:
          path: target/retrobot-1.0-SNAPSHOT-spring-boot.jar
          destination: retrobotbuild/retrobot.jar
      - store_artifacts:
          path: target/scripts
          destination: retrobotbuild/scripts
      - run: wget https://github.com/libgdx/packr/releases/download/packr-2.7.0/packr-all-2.7.0.jar
      - run: touch ./retrobotbuild/start-bot.bat && echo "retrobot.exe" > ./retrobotbuild/start-bot.bat
      - run: java -jar packr-all-2.7.0.jar --platform windows64 --jdk openjdk-12.0.1_windows-x64_bin.zip --executable retrobot --classpath ./retrobotbuild/retrobot.jar --removelibs ./retrobotbuild/retrobot.jar --mainclass org.springframework.boot.loader.JarLauncher --vmargs Xmx1G --minimizejre soft --output build
